#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

# Load the existing configuration only to provide prompt defaults.
SMB_USER="nas"
SMB_SHARE="storage"
HOST_STORAGE_PATH="/mnt/nas"
PUID="1000"
PGID="1000"
SMB_PORT="445"
REQUIRE_MOUNT="true"

if [[ -f .env ]]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

prompt_value() {
    local label="$1"
    local current="$2"
    local value

    printf '%s [%s]: ' "$label" "$current" >&2
    IFS= read -r value
    printf '%s' "${value:-$current}"
}

validate_simple_name() {
    local label="$1"
    local value="$2"
    if [[ ! "$value" =~ ^[A-Za-z0-9._-]+$ ]]; then
        echo "ERROR: $label may contain only letters, numbers, '.', '_' and '-'." >&2
        exit 1
    fi
}

validate_uint() {
    local label="$1"
    local value="$2"
    if [[ ! "$value" =~ ^[0-9]+$ ]]; then
        echo "ERROR: $label must be a non-negative integer." >&2
        exit 1
    fi
}

validate_bool() {
    local value="${1,,}"
    case "$value" in
        true|false) ;;
        *)
            echo "ERROR: REQUIRE_MOUNT must be true or false." >&2
            exit 1
            ;;
    esac
}

yaml_escape() {
    # Escape a string for use inside a YAML double-quoted scalar.
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//\$/\$\$}"
    printf '%s' "$value"
}

echo "sim-nas initialization"
echo

echo "Press Enter to keep the value shown in brackets."
echo

SMB_USER="$(prompt_value "SMB user" "$SMB_USER")"
SMB_SHARE="$(prompt_value "SMB share" "$SMB_SHARE")"
HOST_STORAGE_PATH="$(prompt_value "Host storage path" "$HOST_STORAGE_PATH")"

# Prefer the host Unix account that has the same name as SMB_USER.
# If it exists, use its UID/GID automatically; otherwise fall back to
# manual UID/GID input.
if id "$SMB_USER" >/dev/null 2>&1; then
    PUID="$(id -u "$SMB_USER")"
    PGID="$(id -g "$SMB_USER")"

    echo
    echo "Detected host Unix account for '$SMB_USER':"
    echo "  UID : $PUID"
    echo "  GID : $PGID"
    echo
else
    echo
    echo "Host Unix account '$SMB_USER' was not found."
    echo "Enter UID and GID manually."
    echo

    PUID="$(prompt_value "PUID" "$PUID")"
    PGID="$(prompt_value "PGID" "$PGID")"
fi

SMB_PORT="$(prompt_value "SMB port" "$SMB_PORT")"
REQUIRE_MOUNT="$(prompt_value "Require actual mount (true/false)" "$REQUIRE_MOUNT")"
REQUIRE_MOUNT="${REQUIRE_MOUNT,,}"

validate_simple_name "SMB_USER" "$SMB_USER"
validate_simple_name "SMB_SHARE" "$SMB_SHARE"
validate_uint "PUID" "$PUID"
validate_uint "PGID" "$PGID"
validate_uint "SMB_PORT" "$SMB_PORT"
validate_bool "$REQUIRE_MOUNT"

if [[ "$HOST_STORAGE_PATH" != /* ]]; then
    echo "ERROR: HOST_STORAGE_PATH must be an absolute path." >&2
    exit 1
fi

if (( SMB_PORT < 1 || SMB_PORT > 65535 )); then
    echo "ERROR: SMB_PORT must be between 1 and 65535." >&2
    exit 1
fi

mkdir -p secrets state/samba
chmod 700 secrets

if [[ -s secrets/smb_password ]]; then
    printf 'New SMB password for %s (Enter to keep existing): ' "$SMB_USER"
    IFS= read -r -s PASSWORD
    echo

    if [[ -n "$PASSWORD" ]]; then
        printf 'Confirm new SMB password: '
        IFS= read -r -s PASSWORD_CONFIRM
        echo

        if [[ "$PASSWORD" != "$PASSWORD_CONFIRM" ]]; then
            echo "ERROR: passwords do not match." >&2
            exit 1
        fi

        printf '%s' "$PASSWORD" > secrets/smb_password
    fi
else
    printf 'SMB password for %s: ' "$SMB_USER"
    IFS= read -r -s PASSWORD
    echo
    printf 'Confirm SMB password: '
    IFS= read -r -s PASSWORD_CONFIRM
    echo

    if [[ -z "$PASSWORD" ]]; then
        echo "ERROR: password must not be empty." >&2
        exit 1
    fi

    if [[ "$PASSWORD" != "$PASSWORD_CONFIRM" ]]; then
        echo "ERROR: passwords do not match." >&2
        exit 1
    fi

    printf '%s' "$PASSWORD" > secrets/smb_password
fi

chmod 600 secrets/smb_password

# .env remains the machine-readable configuration used by the helper scripts.
printf -v ENV_PATH '%q' "$HOST_STORAGE_PATH"
cat > .env <<EOF_ENV
# Generated by ./sim-nas init
SMB_USER=$SMB_USER
SMB_SHARE=$SMB_SHARE
HOST_STORAGE_PATH=$ENV_PATH
PUID=$PUID
PGID=$PGID
SMB_PORT=$SMB_PORT
REQUIRE_MOUNT=$REQUIRE_MOUNT
EOF_ENV

ESC_USER="$(yaml_escape "$SMB_USER")"
ESC_SHARE="$(yaml_escape "$SMB_SHARE")"
ESC_PATH="$(yaml_escape "$HOST_STORAGE_PATH")"

# compose.yaml is intentionally rendered with the selected values so the
# deployment definition is self-contained and easy to inspect.
cat > compose.yaml <<EOF_COMPOSE
# Generated by ./sim-nas init. Re-run init to change this file.
name: sim-nas

services:
  smb:
    build:
      context: ./smb
    image: sim-nas:latest
    container_name: sim-nas
    restart: unless-stopped
    ports:
      - "${SMB_PORT}:445"
    environment:
      SMB_USER: "${ESC_USER}"
      SMB_SHARE: "${ESC_SHARE}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - type: bind
        source: "${ESC_PATH}"
        target: /nas/storage
      - type: bind
        source: ./state/samba
        target: /var/lib/samba
    secrets:
      - smb_password
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - sim-nas-net

secrets:
  smb_password:
    file: ./secrets/smb_password

networks:
  sim-nas-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.230.5.0/24
EOF_COMPOSE

cat <<MSG

sim-nas initialized.

SMB user    : $SMB_USER
SMB share   : $SMB_SHARE
Host path   : $HOST_STORAGE_PATH
UID:GID     : $PUID:$PGID
SMB port    : $SMB_PORT
Mount guard : $REQUIRE_MOUNT

Updated:
  .env
  compose.yaml
  secrets/smb_password

Next:
  ./sim-nas check
  ./sim-nas start
MSG